version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: billing_postgres
    restart: always
    environment:
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_pass
      POSTGRES_DB: billing_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - billing_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: billing_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@billing.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"
    depends_on:
      - postgres
    networks:
      - billing_network

volumes:
  postgres_data:

networks:
  billing_network:
    driver: bridge
